# Generated by Django 5.0.7 on 2025-07-27 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_memorization_amount',
            field=models.PositiveIntegerField(default=0, help_text='عدد الآيات أو الأجزاء المحفوظة قبل الانضمام', verbose_name='كمية الحفظ السابقة'),
        ),
        migrations.CreateModel(
            name='MemorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.CharField(max_length=100)),
                ('from_verse', models.PositiveIntegerField()),
                ('to_verse', models.PositiveIntegerField()),
                ('verses_count', models.PositiveIntegerField(editable=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_records', to='students.student')),
            ],
        ),
    ]
