# Generated by Django 5.0.7 on 2025-07-28 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_alter_student_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorizationrecord',
            options={'ordering': ['-date'], 'verbose_name': 'سجل حفظ', 'verbose_name_plural': 'سجلات الحفظ'},
        ),
        migrations.RemoveField(
            model_name='memorizationrecord',
            name='verses_count',
        ),
        migrations.AddField(
            model_name='memorizationrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='from_verse',
            field=models.PositiveIntegerField(verbose_name='من آية'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='موافق عليه'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_records', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='surah',
            field=models.CharField(max_length=100, verbose_name='السورة'),
        ),
        migrations.AlterField(
            model_name='memorizationrecord',
            name='to_verse',
            field=models.PositiveIntegerField(verbose_name='إلى آية'),
        ),
    ]
