# Generated by Django 5.2.4 on 2026-04-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_memorizationrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorizationrecord',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'سجل حفظ', 'verbose_name_plural': 'سجلات الحفظ'},
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
    ]
