# Generated by Django 5.2.4 on 2026-04-26 11:01

import re

import django.db.models.deletion
from django.db import migrations, models


GRADE_KEYWORD_MAP = {
    "اول": 1,
    "أول": 1,
    "ثاني": 2,
    "ثالث": 3,
    "رابع": 4,
    "خامس": 5,
    "سادس": 6,
    "سابع": 7,
    "ثامن": 8,
    "تاسع": 9,
    "عاشر": 10,
    "حادي عشر": 11,
    "الحادي عشر": 11,
    "11th": 11,
}

UNIVERSITY_KEYWORDS = (
    "جامعة",
    "جامعي",
    "university",
    "college",
)


def _normalize_grade_text(value):
    if value is None:
        return ""
    return str(value).strip().lower().translate(str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789"))


def _category_code_for_grade_number(grade_number):
    if grade_number in {1, 2, 3}:
        return "1"
    if grade_number in {4, 5}:
        return "2"
    if grade_number in {6, 7}:
        return "3"
    if grade_number == 8:
        return "4"
    if grade_number in {9, 10, 11}:
        return "5"
    return None


def _infer_category_code(grade_value):
    text = _normalize_grade_text(grade_value)
    if not text:
        return None

    if any(keyword in text for keyword in UNIVERSITY_KEYWORDS):
        return "S"

    match = re.search(r"\d+", text)
    if match:
        return _category_code_for_grade_number(int(match.group()))

    for keyword, grade_number in GRADE_KEYWORD_MAP.items():
        if keyword.lower() in text:
            return _category_code_for_grade_number(grade_number)
    return None


def _backfill_student_category_and_halaqa(apps, schema_editor):
    Category = apps.get_model("halaqas", "Category")
    Halaqa = apps.get_model("halaqas", "Halaqa")
    HalaqaMembership = apps.get_model("halaqas", "HalaqaMembership")
    Student = apps.get_model("students", "Student")
    db_alias = schema_editor.connection.alias

    category_map = {
        category.code: category.id
        for category in Category.objects.using(db_alias).all()
    }

    for student in Student.objects.using(db_alias).all():
        active_membership = (
            HalaqaMembership.objects.using(db_alias)
            .filter(student_id=student.id, is_active=True)
            .order_by("-join_date", "-id")
            .first()
        )

        halaqa_id = active_membership.halaqa_id if active_membership else None
        category_id = None

        if halaqa_id:
            halaqa = Halaqa.objects.using(db_alias).filter(pk=halaqa_id).only("id", "category_id").first()
            if halaqa and halaqa.category_id:
                category_id = halaqa.category_id

        if not category_id:
            category_code = _infer_category_code(student.grade)
            category_id = category_map.get(category_code)
            if halaqa_id and category_id:
                Halaqa.objects.using(db_alias).filter(pk=halaqa_id, category_id__isnull=True).update(
                    category_id=category_id
                )

        Student.objects.using(db_alias).filter(pk=student.id).update(
            halaqa_id=halaqa_id,
            category_id=category_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("halaqas", "0006_category_teacherassignment_alter_halaqa_options_and_more"),
        ("students", "0006_alter_memorizationrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="halaqas.category",
                verbose_name="الفئة",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="halaqa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to="halaqas.halaqa",
                verbose_name="الحلقة الحالية",
            ),
        ),
        migrations.RunPython(_backfill_student_category_and_halaqa, migrations.RunPython.noop),
    ]
