# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_memorization_halaqa(apps, schema_editor):
    HalaqaMembership = apps.get_model("halaqas", "HalaqaMembership")
    MemorizationRecord = apps.get_model("students", "MemorizationRecord")
    Student = apps.get_model("students", "Student")
    db_alias = schema_editor.connection.alias

    for record in MemorizationRecord.objects.using(db_alias).all().iterator():
        student = Student.objects.using(db_alias).filter(pk=record.student_id).only("id", "halaqa_id").first()
        halaqa_id = student.halaqa_id if student else None
        if not halaqa_id:
            membership = (
                HalaqaMembership.objects.using(db_alias)
                .filter(student_id=record.student_id, is_active=True)
                .order_by("-join_date", "-id")
                .first()
            )
            halaqa_id = membership.halaqa_id if membership else None
        if halaqa_id:
            MemorizationRecord.objects.using(db_alias).filter(pk=record.pk).update(halaqa_id=halaqa_id)


class Migration(migrations.Migration):

    dependencies = [
        ("halaqas", "0008_homework_expected_recitation_details"),
        ("students", "0007_student_category_student_halaqa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memorizationrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_memorization_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="memorizationrecord",
            name="halaqa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memorization_records",
                to="halaqas.halaqa",
                verbose_name="الحلقة",
            ),
        ),
        migrations.AddField(
            model_name="memorizationrecord",
            name="homework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memorization_records",
                to="halaqas.homework",
                verbose_name="الواجب المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="memorizationrecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AddField(
            model_name="memorizationrecord",
            name="pages",
            field=models.CharField(blank=True, max_length=80, verbose_name="الصفحات"),
        ),
        migrations.AddField(
            model_name="memorizationrecord",
            name="recitation_type",
            field=models.CharField(
                choices=[("homework", "واجب"), ("extra", "تسميع إضافي")],
                default="extra",
                max_length=20,
                verbose_name="نوع التسميع",
            ),
        ),
        migrations.AlterField(
            model_name="memorizationrecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_memorization_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وافق عليه",
            ),
        ),
        migrations.AlterField(
            model_name="memorizationrecord",
            name="from_verse",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="من آية"),
        ),
        migrations.AlterField(
            model_name="memorizationrecord",
            name="surah",
            field=models.CharField(blank=True, max_length=100, verbose_name="السورة"),
        ),
        migrations.AlterField(
            model_name="memorizationrecord",
            name="to_verse",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="إلى آية"),
        ),
        migrations.RunPython(_backfill_memorization_halaqa, migrations.RunPython.noop),
    ]
