# Generated by Django 5.0.7 on 2025-07-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='halaqa',
            name='shareable_link',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
