# Generated by Django 5.2.4 on 2026-04-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaqas', '0003_alter_halaqamembership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halaqamembership',
            options={'ordering': ['-join_date'], 'verbose_name': 'عضوية الحلقة', 'verbose_name_plural': 'عضويات الحلقات'},
        ),
    ]
