# Generated by Django 5.0.7 on 2026-04-18 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqas', '0004_alter_halaqamembership_options'),
        ('students', '0006_alter_memorizationrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('assignment_type', models.CharField(choices=[('surah', 'سورة'), ('pages', 'صفحات'), ('text', 'واجب نصي')], max_length=20)),
                ('assignment_text', models.CharField(max_length=120)),
                ('assignment_notes', models.CharField(blank=True, max_length=255)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('evaluation', models.CharField(blank=True, choices=[('excellent', 'متقن'), ('completed', 'منجز'), ('partial', 'منجز جزئياً'), ('not_completed', 'غير منجز')], max_length=20)),
                ('evaluation_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_homeworks', to=settings.AUTH_USER_MODEL)),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='halaqas.halaqa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='students.student')),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
            },
        ),
    ]
