# Generated by Django 5.2.4 on 2026-04-26 11:01

import re

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Count


OFFICIAL_CATEGORY_SPECS = [
    ("1", "الفئة 1", "الصفوف 1، 2، 3", 1, False),
    ("2", "الفئة 2", "الصفوف 4، 5", 2, False),
    ("3", "الفئة 3", "الصفوف 6، 7", 3, False),
    ("4", "الفئة 4", "الصف 8", 4, False),
    ("5", "الفئة 5", "الصفوف 9، 10، 11", 5, False),
    ("S", "الفئة S", "طلاب الجامعة", 6, True),
]

GRADE_KEYWORD_MAP = {
    "اول": 1,
    "أول": 1,
    "ثاني": 2,
    "ثالث": 3,
    "رابع": 4,
    "خامس": 5,
    "سادس": 6,
    "سابع": 7,
    "ثامن": 8,
    "تاسع": 9,
    "عاشر": 10,
    "حادي عشر": 11,
    "الحادي عشر": 11,
    "11th": 11,
}

UNIVERSITY_KEYWORDS = (
    "جامعة",
    "جامعي",
    "university",
    "college",
)


def _normalize_grade_text(value):
    if value is None:
        return ""
    return str(value).strip().lower().translate(str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789"))


def _category_code_for_grade_number(grade_number):
    if grade_number in {1, 2, 3}:
        return "1"
    if grade_number in {4, 5}:
        return "2"
    if grade_number in {6, 7}:
        return "3"
    if grade_number == 8:
        return "4"
    if grade_number in {9, 10, 11}:
        return "5"
    return None


def _infer_category_code(grade_value):
    text = _normalize_grade_text(grade_value)
    if not text:
        return None

    if any(keyword in text for keyword in UNIVERSITY_KEYWORDS):
        return "S"

    match = re.search(r"\d+", text)
    if match:
        return _category_code_for_grade_number(int(match.group()))

    for keyword, grade_number in GRADE_KEYWORD_MAP.items():
        if keyword.lower() in text:
            return _category_code_for_grade_number(grade_number)
    return None


def _seed_categories(apps, schema_editor):
    Category = apps.get_model("halaqas", "Category")
    db_alias = schema_editor.connection.alias

    for code, name, grade_span, display_order, is_special in OFFICIAL_CATEGORY_SPECS:
        Category.objects.using(db_alias).update_or_create(
            code=code,
            defaults={
                "name": name,
                "grade_span": grade_span,
                "display_order": display_order,
                "is_special": is_special,
                "notes": "",
            },
        )


def _backfill_halaqa_categories_and_teacher_assignments(apps, schema_editor):
    Category = apps.get_model("halaqas", "Category")
    Halaqa = apps.get_model("halaqas", "Halaqa")
    HalaqaMembership = apps.get_model("halaqas", "HalaqaMembership")
    Teacher = apps.get_model("halaqas", "Teacher")
    TeacherAssignment = apps.get_model("halaqas", "TeacherAssignment")
    Student = apps.get_model("students", "Student")
    db_alias = schema_editor.connection.alias

    _seed_categories(apps, schema_editor)
    category_map = {
        category.code: category.id
        for category in Category.objects.using(db_alias).all()
    }
    category_order = {code: display_order for code, _, _, display_order, _ in OFFICIAL_CATEGORY_SPECS}

    duplicate_memberships = (
        HalaqaMembership.objects.using(db_alias)
        .filter(is_active=True)
        .values("student_id")
        .annotate(active_count=Count("id"))
        .filter(active_count__gt=1)
    )
    for row in duplicate_memberships:
        memberships = list(
            HalaqaMembership.objects.using(db_alias)
            .filter(student_id=row["student_id"], is_active=True)
            .order_by("-join_date", "-id")
        )
        for stale_membership in memberships[1:]:
            stale_membership.is_active = False
            if not stale_membership.end_date:
                stale_membership.end_date = stale_membership.join_date
            stale_membership.save(update_fields=["is_active", "end_date"])

    student_grade_map = {
        student.id: _infer_category_code(student.grade)
        for student in Student.objects.using(db_alias).all().only("id", "grade")
    }

    for halaqa in Halaqa.objects.using(db_alias).all():
        if halaqa.category_id:
            continue

        memberships = list(
            HalaqaMembership.objects.using(db_alias)
            .filter(halaqa_id=halaqa.id, is_active=True)
            .order_by("-join_date", "-id")
        )
        if not memberships:
            memberships = list(
                HalaqaMembership.objects.using(db_alias)
                .filter(halaqa_id=halaqa.id)
                .order_by("-join_date", "-id")
            )

        category_counts = {}
        for membership in memberships:
            category_code = student_grade_map.get(membership.student_id)
            if category_code:
                category_counts[category_code] = category_counts.get(category_code, 0) + 1

        if not category_counts:
            continue

        selected_code = sorted(
            category_counts.items(),
            key=lambda item: (-item[1], category_order.get(item[0], 999), item[0]),
        )[0][0]
        category_id = category_map.get(selected_code)
        if category_id:
            halaqa.category_id = category_id
            halaqa.save(update_fields=["category"])

    through_model = Halaqa.teachers.through
    latest_halaqa_per_teacher = {}
    for relation in through_model.objects.using(db_alias).all().order_by("teacher_id", "-id"):
        latest_halaqa_per_teacher.setdefault(relation.teacher_id, relation.halaqa_id)

    today = django.utils.timezone.localdate()
    for teacher in Teacher.objects.using(db_alias).all():
        teacher_pk = teacher.pk
        selected_halaqa_id = latest_halaqa_per_teacher.get(teacher_pk)
        Teacher.objects.using(db_alias).filter(pk=teacher_pk).update(current_halaqa_id=selected_halaqa_id)

        if selected_halaqa_id:
            through_model.objects.using(db_alias).filter(teacher_id=teacher_pk).exclude(
                halaqa_id=selected_halaqa_id
            ).delete()
            TeacherAssignment.objects.using(db_alias).update_or_create(
                teacher_id=teacher_pk,
                halaqa_id=selected_halaqa_id,
                defaults={
                    "start_date": today,
                    "end_date": None,
                    "is_active": True,
                    "notes": "",
                },
            )
            TeacherAssignment.objects.using(db_alias).filter(teacher_id=teacher_pk).exclude(
                halaqa_id=selected_halaqa_id
            ).update(
                is_active=False,
                end_date=today,
            )
            continue

        through_model.objects.using(db_alias).filter(teacher_id=teacher_pk).delete()
        TeacherAssignment.objects.using(db_alias).filter(teacher_id=teacher_pk).update(
            is_active=False,
            end_date=today,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("halaqas", "0005_homework"),
        ("students", "0006_alter_memorizationrecord_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=2, unique=True, verbose_name="رمز الفئة")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="اسم الفئة")),
                ("grade_span", models.CharField(max_length=80, verbose_name="نطاق الصفوف")),
                ("display_order", models.PositiveSmallIntegerField(default=0, verbose_name="ترتيب العرض")),
                ("is_special", models.BooleanField(default=False, verbose_name="فئة خاصة")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "فئة",
                "verbose_name_plural": "الفئات",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "نقل/إسناد معلم",
                "verbose_name_plural": "نقلات وإسنادات المعلمين",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="halaqa",
            options={"verbose_name": "حلقة", "verbose_name_plural": "الحلقات"},
        ),
        migrations.AddField(
            model_name="teacher",
            name="current_halaqa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_teachers",
                to="halaqas.halaqa",
                verbose_name="الحلقة الحالية",
            ),
        ),
        migrations.AlterField(
            model_name="halaqa",
            name="teachers",
            field=models.ManyToManyField(blank=True, related_name="halaqas", to="halaqas.teacher"),
        ),
        migrations.AddField(
            model_name="halaqa",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="halaqas",
                to="halaqas.category",
                verbose_name="الفئة",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="halaqa",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teacher_assignments", to="halaqas.halaqa"),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="halaqas.teacher"),
        ),
        migrations.RunPython(_backfill_halaqa_categories_and_teacher_assignments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="halaqamembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student",),
                name="unique_active_halaqa_membership_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("teacher",),
                name="unique_active_teacher_assignment_per_teacher",
            ),
        ),
    ]
