# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halaqas", "0007_attendance_recorder_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="expected_recitation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="from_verse",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="pages",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homework",
            name="surah",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homework",
            name="to_verse",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
