# Generated by Django 5.2.4 on 2026-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqas', '0009_plan_total_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAttendanceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رابط حضور الموجه',
                'verbose_name_plural': 'روابط حضور الموجهين',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
